version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - webapp-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb://database:27017/mydatabase
    depends_on:
      - database
    networks:
      - webapp-network

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
